[package]
name = "gamecrab"
version = "0.1.0"
authors = ["olivia"]

[dependencies]
piston_window = "0.81.0"
image = "0.20.1"
fps_counter = "0.2.0"
time = "0.1"
sdl2 = "0.29"
nfd = { git = "https://github.com/saurvs/nfd-rs.git" }

[profile.release]

[profile.dev]
debug = true
